import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowRight, Flame, Truck, Clock, UtensilsCrossed } from 'lucide-react';
import { api } from '@/lib/api';
import type { MenuItem, Category } from '@/types';
import { FoodCard } from '@/components/FoodCard';
import { ItemModal } from '@/components/ItemModal';
import { useCart } from '@/context/CartContext';
import { useToast } from '@/context/ToastContext';
import { useRestaurant } from '@/context/RestaurantContext';

const CATEGORY_IMAGES: Record<string, string> = {
  burgers: 'https://images.pexels.com/photos/20722041/pexels-photo-20722041.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  'fried-chicken': 'https://images.pexels.com/photos/1860202/pexels-photo-1860202.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  wraps: 'https://images.pexels.com/photos/13292629/pexels-photo-13292629.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  fries: 'https://images.pexels.com/photos/4109234/pexels-photo-4109234.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  'pop-corn': 'https://images.pexels.com/photos/8998354/pexels-photo-8998354.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  prawns: 'https://images.pexels.com/photos/6426095/pexels-photo-6426095.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  wings: 'https://images.pexels.com/photos/8862753/pexels-photo-8862753.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  drinks: 'https://images.pexels.com/photos/13759884/pexels-photo-13759884.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  'value-bucket-meals': 'https://images.pexels.com/photos/27605381/pexels-photo-27605381.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  'bucket-combos': 'https://images.pexels.com/photos/12339076/pexels-photo-12339076.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  'value-meal': 'https://images.pexels.com/photos/10813356/pexels-photo-10813356.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
  'value-combo': 'https://images.pexels.com/photos/17121400/pexels-photo-17121400.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90',
};

const CATEGORY_FALLBACK = 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg?auto=compress&cs=tinysrgb&w=1200&q=90';

export function Home() {
  const [bestsellers,setBestsellers]=useState<MenuItem[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [loading,setLoading]=useState(true); const [selectedItem,setSelectedItem]=useState<MenuItem|null>(null); const {addItem}=useCart(); const {show}=useToast(); const {settings}=useRestaurant(); const navigate=useNavigate();
  useEffect(()=>{(async()=>{try{const [b,c]=await Promise.all([api<{data:MenuItem[]}>('/api/menu?bestseller=true'),api<{data:Category[]}>('/api/categories')]);setBestsellers(b.data);setCategories(c.data);}catch(e){console.error(e);show('Failed to load menu','error')}finally{setLoading(false)}})()},[show]);
  const handleQuickAdd=(item:MenuItem)=>{if(item.customizations?.length){setSelectedItem(item)}else{addItem(item,1,[]);show(`${item.name} added to cart`,'success')}};
  return <div className="animate-fade-in">
    <section className="relative min-h-[85vh] flex items-center overflow-hidden bg-lsd-blue-deep"><div className="absolute inset-0"><img src="https://images.pexels.com/photos/18987002/pexels-photo-18987002.jpeg?auto=compress&cs=tinysrgb&h=900&w=1400" alt="LSD burgers" className="w-full h-full object-cover opacity-50"/><div className="absolute inset-0 bg-gradient-to-br from-lsd-blue-deep via-lsd-blue-deep/80 to-lsd-blue/40"/></div><div className="relative max-w-7xl mx-auto px-4 sm:px-6 w-full"><div className="max-w-xl space-y-6 animate-slide-up"><div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/10 border border-white/20 backdrop-blur-sm"><Flame className="w-4 h-4 text-lsd-accent"/><span className="text-xs font-bold text-white uppercase tracking-widest">Now Open in Okhla</span></div><h1 className="font-display text-6xl sm:text-7xl md:text-8xl leading-[0.9] text-white">LIKE<br/>SOMETHING<br/><span className="text-lsd-accent">DOPE?</span></h1><p className="text-lg text-blue-100 max-w-md">Burgers. Crispy Chicken. Big Flavours. The doppest fast food in Jamia Nagar.</p><div className="flex flex-col sm:flex-row gap-3"><button onClick={()=>navigate('/menu')} className="btn-primary !bg-white !text-lsd-blue hover:!bg-blue-50 text-base px-8 py-4">Order Now <ArrowRight className="w-5 h-5"/></button><button onClick={()=>navigate('/menu')} className="btn-secondary !bg-transparent !text-white !border-white hover:!bg-white hover:!text-lsd-blue text-base px-8 py-4">Explore Menu</button></div><div className="flex items-center gap-6 pt-2"><div className="flex items-center gap-2 text-sm text-blue-100"><Truck className="w-4 h-4 text-lsd-accent"/>Free delivery over {settings?`₹${settings.min_order_amount}`:'₹99'}</div><div className="flex items-center gap-2 text-sm text-blue-100"><Clock className="w-4 h-4 text-lsd-accent"/>Open till {settings?.closing_time||'late'}</div></div></div></div></section>
    <section className="bg-lsd-blue text-white py-3"><div className="max-w-7xl mx-auto px-4 flex flex-wrap items-center justify-center gap-x-8 gap-y-1 text-center">{['Big Bold Flavours','Crispy Fried Chicken','Fresh Burgers Daily','Fast Delivery'].map((t,i)=><span key={i} className="font-display text-sm tracking-wide">{t}</span>)}</div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 py-16"><div className="flex items-end justify-between mb-8"><div><p className="section-eyebrow mb-1">Most Loved</p><h2 className="font-display text-4xl sm:text-5xl tracking-tight text-lsd-gray-900">The Dopdest Picks</h2></div><button onClick={()=>navigate('/menu')} className="hidden sm:flex items-center gap-1 text-sm text-lsd-blue font-semibold hover:gap-2 transition-all">View All <ArrowRight className="w-4 h-4"/></button></div>{loading?<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">{Array.from({length:4}).map((_,i)=><div key={i} className="card"><div className="skeleton h-44"/><div className="p-3.5 space-y-2"><div className="skeleton h-4 w-3/4"/><div className="skeleton h-3 w-full"/><div className="skeleton h-6 w-1/2"/></div></div>)}</div>:<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">{bestsellers.map(item=><FoodCard key={item.id} item={item} onAdd={handleQuickAdd} onQuickAdd={handleQuickAdd} onClick={setSelectedItem}/>)}</div>}</section>
    <section className="bg-[#f7f8fa] border-y border-lsd-gray-100 py-16 sm:py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6"><div className="flex items-end justify-between mb-8 sm:mb-10"><div><p className="section-eyebrow mb-1">Explore the menu</p><h2 className="font-display text-4xl sm:text-5xl tracking-tight text-lsd-gray-900">What are you craving?</h2></div><button onClick={()=>navigate('/menu')} className="hidden sm:flex items-center gap-1 text-sm text-lsd-blue font-semibold hover:gap-2 transition-all">Full Menu <ArrowRight className="w-4 h-4"/></button></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4">{categories.map(cat=><button key={cat.id} onClick={()=>navigate(`/menu?cat=${cat.slug}`)} className="group relative h-36 sm:h-44 lg:h-48 rounded-2xl overflow-hidden bg-lsd-blue-deep text-left shadow-sm hover:shadow-xl transition-all duration-300 hover:-translate-y-1"><img src={CATEGORY_IMAGES[cat.slug]||CATEGORY_FALLBACK} alt={cat.name} className="absolute inset-0 w-full h-full object-cover transition-transform duration-500 group-hover:scale-105" loading="lazy"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/25 to-black/5"/><div className="absolute inset-x-0 bottom-0 p-4 sm:p-5"><span className="block text-white font-display text-lg sm:text-xl leading-tight">{cat.name}</span><span className="mt-1 inline-flex items-center gap-1 text-[11px] font-semibold uppercase tracking-wider text-white/70 group-hover:text-white transition-colors">Explore <ArrowRight className="w-3 h-3 transition-transform group-hover:translate-x-1"/></span></div></button>)}</div><button onClick={()=>navigate('/menu')} className="sm:hidden mt-6 w-full flex items-center justify-center gap-2 rounded-xl border border-lsd-gray-200 bg-white py-3 text-sm font-semibold text-lsd-blue">View Full Menu <ArrowRight className="w-4 h-4"/></button></div></section>
    <section className="max-w-7xl mx-auto px-4 sm:px-6 pb-16"><div className="relative rounded-3xl overflow-hidden bg-lsd-blue-deep shadow-blue"><img src="https://images.pexels.com/photos/5488052/pexels-photo-5488052.jpeg?auto=compress&cs=tinysrgb&h=600&w=1400" alt="LSD combo meal" className="w-full h-48 sm:h-64 object-cover opacity-40"/><div className="absolute inset-0 bg-gradient-to-r from-lsd-blue-deep via-lsd-blue-deep/80 to-transparent flex items-center"><div className="p-8 sm:p-12 max-w-md space-y-3"><UtensilsCrossed className="w-10 h-10 text-lsd-accent"/><h3 className="font-display text-3xl sm:text-4xl text-white">Hungry Yet?</h3><p className="text-sm text-blue-100">Order your favourite LSD meal now and get it delivered hot to your door.</p><button onClick={()=>navigate('/menu')} className="btn-primary !bg-white !text-lsd-blue hover:!bg-blue-50">Start Ordering <ArrowRight className="w-4 h-4"/></button></div></div></div></section>
    <ItemModal item={selectedItem} onClose={()=>setSelectedItem(null)}/>
  </div>;
}
