import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';

const app = express();
const PORT = Number(process.env.PORT || 5000);
const JWT_SECRET = process.env.JWT_SECRET;
const allowedOrigins = (process.env.CLIENT_URL || '').split(',').map(s => s.trim()).filter(Boolean);

app.use(helmet());
app.use(cors({ origin: (origin, cb) => !origin || !allowedOrigins.length || allowedOrigins.includes(origin) ? cb(null, true) : cb(new Error('CORS blocked')), credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(morgan('combined'));

const userSchema = new mongoose.Schema({ email:{type:String,required:true,unique:true,lowercase:true,trim:true}, passwordHash:{type:String,required:true}, name:{type:String,required:true,trim:true}, phone:{type:String,default:''}, is_admin:{type:Boolean,default:false} }, { timestamps:{createdAt:'created_at',updatedAt:'updated_at'} });
const categorySchema = new mongoose.Schema({ name:{type:String,required:true}, slug:{type:String,required:true,unique:true}, sort_order:{type:Number,default:0}, icon:{type:String,default:''} }, {timestamps:true});
const menuSchema = new mongoose.Schema({ category_id:{type:mongoose.Schema.Types.ObjectId,ref:'Category'}, name:{type:String,required:true}, description:{type:String,default:''}, price:{type:Number,required:true}, image_url:{type:String,default:''}, is_veg:{type:Boolean,default:true}, is_bestseller:{type:Boolean,default:false}, is_available:{type:Boolean,default:true}, sort_order:{type:Number,default:0}, customizations:{type:Array,default:[]} }, {timestamps:{createdAt:'created_at',updatedAt:'updated_at'}});
const settingsSchema = new mongoose.Schema({ _id:{type:Number,default:1}, is_open:{type:Boolean,default:true}, delivery_enabled:{type:Boolean,default:true}, pickup_enabled:{type:Boolean,default:true}, delivery_charge:{type:Number,default:30}, min_order_amount:{type:Number,default:99}, opening_time:{type:String,default:'11:00'}, closing_time:{type:String,default:'23:00'}, phone:{type:String,default:''}, address:{type:String,default:''}, name:{type:String,default:'LSD Burgers'}, tagline:{type:String,default:'Like Something Dope?'} });
const orderItemSchema = new mongoose.Schema({ menu_item_id:String, name:String, image_url:String, price:Number, quantity:Number, customizations:Array, item_total:Number });
const orderSchema = new mongoose.Schema({ user_id:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true}, order_number:{type:String,unique:true}, status:{type:String,default:'placed'}, subtotal:Number, delivery_charge:Number, discount:Number, total:Number, customer_name:String, customer_phone:String, delivery_type:String, address:String, address_details:String, notes:String, payment_method:String, order_items:[orderItemSchema] }, {timestamps:{createdAt:'created_at',updatedAt:'updated_at'}});
const User=mongoose.model('User',userSchema), Category=mongoose.model('Category',categorySchema), MenuItem=mongoose.model('MenuItem',menuSchema), RestaurantSettings=mongoose.model('RestaurantSettings',settingsSchema), Order=mongoose.model('Order',orderSchema);

const userOut = u => ({id:u._id.toString(),email:u.email,name:u.name,phone:u.phone,is_admin:u.is_admin,created_at:u.created_at});
const tokenFor = u => jwt.sign({id:u._id.toString()}, JWT_SECRET, {expiresIn:'30d'});
const orderOut = o => ({...o.toObject(), id:o._id.toString(), order_items:(o.order_items||[]).map(x=>({...x.toObject(),id:x._id.toString()}))});
const menuOut = i => { const x=i.toObject(); const c=x.category_id && typeof x.category_id==='object' ? x.category_id : null; return {...x,id:i._id.toString(),category_id:c?c._id.toString():x.category_id,category:c?{...c,id:c._id.toString()}:undefined}; };

async function auth(req,res,next){ try { const h=req.headers.authorization||''; const t=h.startsWith('Bearer ')?h.slice(7):null; if(!t)return res.status(401).json({success:false,message:'Authentication required'}); const p=jwt.verify(t,JWT_SECRET); const u=await User.findById(p.id); if(!u)return res.status(401).json({success:false,message:'User not found'}); req.user=u; next(); } catch { res.status(401).json({success:false,message:'Invalid or expired token'}); } }
const adminOnly=(req,res,next)=>req.user?.is_admin?next():res.status(403).json({success:false,message:'Admin access required'});

app.get('/api/health',(_q,r)=>r.json({success:true,message:'API is healthy',timestamp:new Date().toISOString()}));
app.get('/api/health/db',(_q,r)=>r.json({success:true,connected:mongoose.connection.readyState===1}));

app.post('/api/auth/signup',async(req,res)=>{try{const {email,password,name,phone}=req.body;if(!email||!password||!name||!phone)return res.status(400).json({success:false,message:'Name, phone, email and password are required'});if(String(password).length<6)return res.status(400).json({success:false,message:'Password must be at least 6 characters'});const e=String(email).trim().toLowerCase();if(await User.exists({email:e}))return res.status(409).json({success:false,message:'An account with this email already exists'});const u=await User.create({email:e,passwordHash:await bcrypt.hash(String(password),12),name:String(name).trim(),phone:String(phone).trim()});res.status(201).json({success:true,token:tokenFor(u),user:userOut(u)});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to create account'});}});
app.post('/api/auth/login',async(req,res)=>{try{const u=await User.findOne({email:String(req.body.email||'').trim().toLowerCase()});if(!u||!(await bcrypt.compare(String(req.body.password||''),u.passwordHash)))return res.status(401).json({success:false,message:'Invalid email or password'});res.json({success:true,token:tokenFor(u),user:userOut(u)});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to sign in'});}});
app.get('/api/auth/me',auth,(req,res)=>res.json({success:true,user:userOut(req.user)}));
app.put('/api/auth/profile',auth,async(req,res)=>{try{req.user.name=String(req.body.name??req.user.name).trim();req.user.phone=String(req.body.phone??req.user.phone).trim();await req.user.save();res.json({success:true,user:userOut(req.user)});}catch{res.status(500).json({success:false,message:'Failed to update profile'});}});

app.get('/api/categories',async(_q,r)=>r.json({success:true,data:await Category.find().sort({sort_order:1})}));
app.post('/api/admin/categories',auth,adminOnly,async(req,res)=>{try{const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({success:false,message:'Category name is required'});const slug=String(req.body.slug||name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');const c=await Category.create({name,slug,sort_order:Number(req.body.sort_order)||0,icon:req.body.icon||''});res.status(201).json({success:true,data:c});}catch{res.status(400).json({success:false,message:'Failed to create category'});}});
app.put('/api/admin/categories/:id',auth,adminOnly,async(req,res)=>{try{const c=await Category.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!c)return res.status(404).json({success:false,message:'Category not found'});res.json({success:true,data:c});}catch{res.status(400).json({success:false,message:'Failed to update category'});}});
app.delete('/api/admin/categories/:id',auth,adminOnly,async(req,res)=>{try{await Category.findByIdAndDelete(req.params.id);res.json({success:true});}catch{res.status(400).json({success:false,message:'Failed to delete category'});}});

app.get('/api/menu',async(req,res)=>{try{const f={is_available:true};if(req.query.bestseller==='true')f.is_bestseller=true;if(req.query.category){const c=await Category.findOne({slug:req.query.category});if(c)f.category_id=c._id;}const a=await MenuItem.find(f).sort({sort_order:1}).populate('category_id');res.json({success:true,data:a.map(menuOut)});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to load menu'});}});
app.get('/api/admin/menu',auth,adminOnly,async(_q,r)=>{try{const a=await MenuItem.find().sort({sort_order:1}).populate('category_id');r.json({success:true,data:a.map(menuOut)});}catch{r.status(500).json({success:false,message:'Failed to load admin menu'});}});
app.post('/api/admin/menu',auth,adminOnly,async(req,res)=>{try{const i=await MenuItem.create(req.body);const x=await i.populate('category_id');res.status(201).json({success:true,data:menuOut(x)});}catch{res.status(400).json({success:false,message:'Failed to create item'});}});
app.put('/api/admin/menu/:id',auth,adminOnly,async(req,res)=>{try{const i=await MenuItem.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true}).populate('category_id');if(!i)return res.status(404).json({success:false,message:'Item not found'});res.json({success:true,data:menuOut(i)});}catch{res.status(400).json({success:false,message:'Failed to update item'});}});
app.delete('/api/admin/menu/:id',auth,adminOnly,async(req,res)=>{try{await MenuItem.findByIdAndDelete(req.params.id);res.json({success:true});}catch{res.status(400).json({success:false,message:'Failed to delete item'});}});

app.get('/api/settings',async(_q,r)=>{try{let s=await RestaurantSettings.findById(1);if(!s)s=await RestaurantSettings.create({_id:1});r.json({success:true,data:{...s.toObject(),id:1}});}catch{r.status(500).json({success:false,message:'Failed to load settings'});}});
app.put('/api/settings',auth,adminOnly,async(req,res)=>{try{const allowed=['is_open','delivery_enabled','pickup_enabled','delivery_charge','min_order_amount','opening_time','closing_time','phone','address','name','tagline'];const data=Object.fromEntries(Object.entries(req.body).filter(([k])=>allowed.includes(k)));const s=await RestaurantSettings.findByIdAndUpdate(1,{$set:data},{new:true,upsert:true,runValidators:true});res.json({success:true,data:{...s.toObject(),id:1}});}catch{res.status(400).json({success:false,message:'Failed to update settings'});}});

app.post('/api/orders',auth,async(req,res)=>{try{const {items,...body}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({success:false,message:'Order must contain items'});const s=await RestaurantSettings.findById(1);if(s&&!s.is_open)return res.status(400).json({success:false,message:'Restaurant is currently closed'});const o=await Order.create({...body,user_id:req.user._id,order_items:items,order_number:`LSD-${Date.now().toString().slice(-8)}`,status:'placed'});res.status(201).json({success:true,data:orderOut(o)});}catch(e){console.error(e);res.status(500).json({success:false,message:'Failed to place order'});}});
app.get('/api/orders',auth,async(req,res)=>{try{const o=await Order.find({user_id:req.user._id}).sort({created_at:-1});res.json({success:true,data:o.map(orderOut)});}catch{res.status(500).json({success:false,message:'Failed to load orders'});}});
app.get('/api/orders/:id',auth,async(req,res)=>{try{const filter=req.user.is_admin?{_id:req.params.id}:{_id:req.params.id,user_id:req.user._id};const o=await Order.findOne(filter);if(!o)return res.status(404).json({success:false,message:'Order not found'});res.json({success:true,data:orderOut(o)});}catch{res.status(404).json({success:false,message:'Order not found'});}});
app.get('/api/admin/orders',auth,adminOnly,async(_q,r)=>{try{const o=await Order.find().sort({created_at:-1}).limit(100).populate('user_id','name email phone');r.json({success:true,data:o.map(x=>({...orderOut(x),customer:x.user_id?{name:x.user_id.name,email:x.user_id.email,phone:x.user_id.phone}:undefined}))});}catch{r.status(500).json({success:false,message:'Failed to load orders'});}});
app.patch('/api/admin/orders/:id/status',auth,adminOnly,async(req,res)=>{try{const allowed=['placed','confirmed','preparing','ready','out_for_delivery','delivered','cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({success:false,message:'Invalid status'});const o=await Order.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});if(!o)return res.status(404).json({success:false,message:'Order not found'});res.json({success:true,data:orderOut(o)});}catch{res.status(400).json({success:false,message:'Failed to update order'});}});
app.get('/api/admin/stats',auth,adminOnly,async(_q,r)=>{try{const start=new Date();start.setHours(0,0,0,0);const today=await Order.find({created_at:{$gte:start}});const all=await Order.find({},'order_items');const m=new Map();for(const o of all)for(const i of (o.order_items||[]))m.set(i.name,(m.get(i.name)||0)+Number(i.quantity||0));r.json({success:true,data:{todayOrders:today.length,todayRevenue:today.filter(o=>o.status==='delivered').reduce((s,o)=>s+Number(o.total||0),0),pending:today.filter(o=>!['delivered','cancelled'].includes(o.status)).length,completed:today.filter(o=>o.status==='delivered').length,cancelled:today.filter(o=>o.status==='cancelled').length,popularItems:[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([name,count])=>({name,count})),recentOrders:(await Order.find().sort({created_at:-1}).limit(5)).map(orderOut)}});}catch{r.status(500).json({success:false,message:'Failed to load dashboard stats'});}});

app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({success:false,message:err.message||'Internal server error'});});

async function start(){if(!process.env.MONGODB_URI)throw new Error('MONGODB_URI is required');if(!JWT_SECRET)throw new Error('JWT_SECRET is required');await mongoose.connect(process.env.MONGODB_URI);console.log('MongoDB connected');await RestaurantSettings.updateOne({_id:1},{$setOnInsert:{_id:1}},{upsert:true});app.listen(PORT,'0.0.0.0',()=>console.log(`LSD Burgers API listening on port ${PORT}`));}
start().catch(e=>{console.error('Failed to start server:',e);process.exit(1);});
